spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
    username: ${MYSQL_USER}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: create
    show-sql: true
  flyway:
    enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 20MB
bot:
#  token: ${TELEGRAM_BOT_TOKEN}
  token: ${TELEGRAM_BOT_TOKEN_DEV}
  chatId: ${TELEGRAM_CHAT_ID}
logging:
  file:
    name: bot.log
  level:
    root: info